# Generated by Django 5.0 on 2023-12-19 12:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="participant",
            name="monthly_fee_paid",
        ),
        migrations.AddField(
            model_name="participant",
            name="email",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="participant",
            name="enrolled_date",
            field=models.DateField(),
        ),
    ]
