# Generated by Django 5.0 on 2023-12-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_remove_participant_monthly_fee_paid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="enrolled_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
